### ISSUE TITLE
Making the DateRangePicker working with HasFiltersAction (action modal)

### ISSUE THREAD

**Issue by mgralikowski** [malzariey/filament-daterangepicker-filter#141]
Hi, I am trying to use `DateRangePicker` in the filter form in a custom page/dashboard. I think this function was recently added in the Filament.
https://filamentphp.com/docs/3.x/panels/dashboard#filtering-widget-data-using-an-action-modal
Generally, it is almost the same concept as in tables, the only difference is where the modal is displayed, in this case, it is a full page modal displayed on the right side of the page. 

It works but there are some issues:

1) Frontend issue:
![image](https://github.com/user-attachments/assets/8170c0e0-48c2-4790-be99-b460e2cef857)
It could be fixed by re-rendering the date picker when the modal is fully loaded. It is rendered correctly if the input is clicked manually.

2) I noticed weird behavior, when I use the date picker, for 1-2 seconds the main button is inactive, it is even noticeable by cursor type:
![image](https://github.com/user-attachments/assets/09dd7783-c13e-455a-b41c-b9048b709866)
After 1-2 second:
![image](https://github.com/user-attachments/assets/49152161-c37e-4dce-a284-2d22275ced4c)

So any change requires a bit of waiting before submitting :)

3) `format()` is completely ignored. In the URL filters are built as they are displayed in the form. It is not critical as I decided to change displayFormat to be aligned with the PHP date. 

Here is some code I use. Please notice that the `HasFiltersAction` trait is just a wrapper for the `HasFilters`. 

```php
<?php 
class Metrics extends Page

    use HasFiltersAction;

    public function persistsFiltersInSession(): bool
    {
        return false;
    }

    public function getActiveFiltersCount(): int
    {
        return count(array_filter($this->filters ?? []));
    }

    protected function getHeaderActions(): array
    {
        return [
            FilterAction::make()
                ->form([
                    DateRangePicker::make('range')
                        ->label('Date range')
                        ->maxDate(now())
                        ->displayFormat('YYYY-MM-DD')
                        ->format('Y-m-d') // it doesn't work
                        ->autofocus(false),
                ])
                ->label(fn () => $this->getActiveFiltersCount() > 0
                    ? 'Active filters (' . $this->getActiveFiltersCount() . ')'
                    : 'Enable filtering')
                ->color(fn () => $this->getActiveFiltersCount() > 0 ? 'primary' : 'gray'),
        ];
    }

**Comment by mgralikowski** [comment]
The 2 problem - quick fix:
` ->modalAutofocus(false)`

**Comment by malzariey** [comment]
First Issue:
- Fixed using  `->modalAutofocus(false)` as the modal is auto focusing on the field. 
- Another workaround would be using the DateRangePicker as a second field in the FilterAction

(Cant be addressed at the moment as the behavior is due to opeing the picker before the modal is fully opened)

Second Issue, is not related to the Date Range Picker does not control the apply button. Might be related to some calculation or rendering happening behind the scenes.

Third Issue:
Format <- is only used as Carbon format when getting the date from the display Format. Mostly used in filtering dates using DateRangeFilter

I have updated the picker to include the autofocus in the input (Only fixing the first issue on the modal first open)

Thank you for your interest using DateRangePicker.
